create table public.feed_eventos (
  id bigint generated by default as identity primary key,
  sala_id text not null,
  jugador_id integer not null,
  tipo text not null check (tipo in ('captura', 'muerte')),
  save_pokemon_id text not null,
  pokemon_name text not null,
  pokemon_id integer,
  ruta text not null,
  is_shiny boolean not null default false,
  ocurrido_en timestamptz not null,
  created_at timestamptz not null default now(),
  constraint feed_eventos_unique_event
    unique (sala_id, jugador_id, save_pokemon_id, tipo)
);

alter table public.feed_eventos enable row level security;

create policy "feed_eventos_select_room"
  on public.feed_eventos
  for select
  to anon, authenticated
  using (sala_id = 'anil-locke-2026');

create policy "feed_eventos_insert_room"
  on public.feed_eventos
  for insert
  to anon, authenticated
  with check (sala_id = 'anil-locke-2026');

grant select, insert on public.feed_eventos to anon, authenticated;
grant usage, select on sequence public.feed_eventos_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'feed_eventos'
  ) then
    alter publication supabase_realtime add table public.feed_eventos;
  end if;
end
$$;
