create table if not exists public.torneo_historial (
  id bigint generated by default as identity primary key,
  sala_id text not null,
  nombre text not null default 'Torneo',
  campeon text not null default 'Por determinar',
  max_participants integer not null default 0,
  bracket_data jsonb not null default '[]'::jsonb
);

alter table public.torneo
  add column if not exists tournament_key uuid not null default gen_random_uuid();

alter table public.torneo_historial
  add column if not exists tournament_key uuid,
  add column if not exists nombre text not null default 'Torneo',
  add column if not exists campeon text not null default 'Por determinar',
  add column if not exists max_participants integer not null default 0,
  add column if not exists tournament_name text not null default 'Torneo',
  add column if not exists positions jsonb not null default '[]'::jsonb,
  add column if not exists saved_at timestamptz not null default now();

update public.torneo_historial
set max_participants = 0
where max_participants is null;

alter table public.torneo_historial
  alter column max_participants set default 0,
  alter column max_participants set not null;

update public.torneo_historial
set tournament_key = gen_random_uuid()
where tournament_key is null;

alter table public.torneo_historial
  alter column tournament_key set default gen_random_uuid(),
  alter column tournament_key set not null;

create unique index if not exists torneo_historial_tournament_key_key
  on public.torneo_historial (tournament_key);

alter table public.torneo_historial enable row level security;

drop policy if exists "Anyone can read tournament history" on public.torneo_historial;
create policy "Anyone can read tournament history"
  on public.torneo_historial
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can save tournament history" on public.torneo_historial;
create policy "Anyone can save tournament history"
  on public.torneo_historial
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Anyone can update tournament history" on public.torneo_historial;
create policy "Anyone can update tournament history"
  on public.torneo_historial
  for update
  to anon, authenticated
  using (true)
  with check (true);

grant select, insert, update on public.torneo_historial to anon, authenticated;
